import { Inter } from "next/font/google";
import { getData } from "./page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: '',
  description: "Generated by create next app",
};

getData().then(res=>metadata.title = res.title)

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
